- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!, bigg01"

    - name: Package installation
      dnf:
        name:
          - bash
          - sshd
        state: latest
